all: 
	gcc -Wall -o main zad0.c
	gcc -Wall -o main zad1.c
	gcc -Wall -o main zad2.c
	gcc -Wall -o main zad3.c
	gcc -Wall -o main zad4.c
	gcc -Wall -o main zad5.c
	gcc -Wall -o main zad6.c
	gcc -Wall -o main zad7.c
	gcc -Wall -o main zad8.c
	gcc -Wall -o main zad9.c
	gcc -Wall -o main zad10.c
	gcc -Wall -o main zad11.c
	gcc -Wall -o main zad12.c
