all:
	gcc -Wall -o zad1 zad1.c
	gcc -Wall -o zad2 zad2.c
	gcc -Wall -o zad3 zad3.c
	gcc -Wall -o zad4 zad4.c
	gcc -Wall -o zad5 zad5.c
	gcc -Wall -o zad6 zad6.c
	gcc -Wall -o zad7 zad7.c
	gcc -Wall -o zad8 zad8.c
	gcc -Wall -o zad9 zad9.c
